name: Deploy to Subdomain (sales.shiphit.com)

on:
  push:
    branches:
      - salesv4-db-updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Clean first (before upload)
      - name: Clean Hostinger sales folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: u331486718
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          port: 65002
          script: |
            rm -rf /home/u331486718/domains/sales.shiphit.com/public_html/*

      # Upload dist folder
      - name: Upload dist folder to Hostinger
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: u331486718
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          port: 65002
          source: "dist/*"
          target: "/home/u331486718/domains/sales.shiphit.com/public_html"
